<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="UsesCases\Expenses\Reports\Excel\ResourcePaymentTayp.fr.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="UsesCases\Expenses\Reports\Pdf\Fonts\Raleway-Black.ttf" />
    <None Remove="UsesCases\Expenses\Reports\Pdf\Fonts\Raleway-Regular.ttf" />
    <None Remove="UsesCases\Expenses\Reports\Pdf\Fonts\WorkSans-Black.ttf" />
    <None Remove="UsesCases\Expenses\Reports\Pdf\Fonts\WorkSans-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UsesCases\Expenses\Reports\Pdf\Fonts\Raleway-Black.ttf" />
    <EmbeddedResource Include="UsesCases\Expenses\Reports\Pdf\Fonts\Raleway-Regular.ttf" />
    <EmbeddedResource Include="UsesCases\Expenses\Reports\Pdf\Fonts\WorkSans-Black.ttf" />
    <EmbeddedResource Include="UsesCases\Expenses\Reports\Pdf\Fonts\WorkSans-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashFlow.communication\CashFlow.communication.csproj" />
    <ProjectReference Include="..\CashFlow.Domain\CashFlow.Domain.csproj" />
    <ProjectReference Include="..\CashFlow.Exception\CashFlow.Exception.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Logo\logo_csharp_62x62.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
